name: cdc_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: 1.1.0
  shared_preferences: 2.2.1
  fluttertoast: 8.2.2
  google_fonts: 6.1.0
  smooth_page_indicator: 1.1.0
  page_transition: 2.1.0
  dotted_border: 2.1.0
  image_picker: 1.0.4
  firebase_core: 2.15.0
  firebase_auth: 4.7.2
  pinput: 3.0.1
  jwt_decode: 0.3.1
  getwidget: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

